javascript:(function() {
    var s = document.createElement('div');
    s.innerHTML = 'Loading...';
    s.style.color = 'black';
    s.style.padding = '5px';
    s.style.margin = '5px';
    s.style.position = 'fixed';
    s.style.zIndex = '9999';
    s.style.fontSize = '24px';
    s.style.border = '1px solid black';
    s.style.right = '5px';
    s.style.top = '5px';
    s.setAttribute('class', 'selector_gadget_loading');
    s.style.background = 'white';
    document.body.appendChild(s);
    s = document.createElement('script');
    s.setAttribute('type', 'text/javascript');
    s.setAttribute('src', 'http://localhost/selectorgadgetCustom/lib/selectorgadgetNotSuggestion.js?raw=true');
    document.head.appendChild(s);
})();